#!/bin/bash

. $(dirname $0)/common.sh

if [ $# -ne 3 ]; then
    echo "usage: $(basename $0) UNPARSED_ORIG_DIR PATCHED_DIR OUT_DIFF"
    exit 0
fi

ORIG_DIR=$1
PATCHED_DIR=$2
OUT=$3

FILES=$(find -L ${PATCHED_DIR} \( -not -type l -and -type f \) -name *.java.orig -print)

array=($FILES)

NFILES=${#array[*]}

if [ ${NFILES} -eq 0 ]; then
    echo "no source files found"
    exit 0
fi

echo "${NFILES} source files found"

PATCHED_DIR_PAT=${PATCHED_DIR%%/}/
ORIG_DIR_PAT=${ORIG_DIR%%/}

rm -f ${OUT}

echo "comparing..."

for f in $FILES; do
    ff=${f%.orig}
    rpath=${ff#$PATCHED_DIR_PAT}
    if [[ $rpath == target/* ]]; then
        continue
    fi
    orig=${ORIG_DIR_PAT}/${rpath}
    if grep -q '// generated by Diff/AST Java Unparser' ${orig}; then
        echo "already unparsed: ${orig}"
    else
        echo "unparsing ${orig}..."
        ${CCA_HOME}/bin/diffast -parseonly -dump:src -dump:src:out ${orig} ${orig}
    fi
    diff -uB ${orig} ${ff} >> ${OUT}
    ${CCA_SCRIPTS_DIR}/java_token_diff.py ${orig} ${ff}
done

echo "done."
